PUT http://localhost:5000/api/cafeteria/dependiente/17/

Content-Type: application/json

{
"nombre":"sheila fundora galloso",
"numeroT":"2222",
"cafeteria_id":2
}


###
GET http://localhost:5000/api/cafeteria/dependiente/
Content-Type: application/json
